name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16-dind
        privileged: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
          pip install -e rootzengine/
      - name: Lint
        run: flake8 .
      - name: Test sonic-codex
        run: pytest tests
      - name: Test rootzengine
        run: pytest rootzengine/tests
      - name: Build Docker image
        run: docker build -t sonic-codex:ci .
