# Production configuration for RootzEngine

# Audio processing settings
audio:
  sample_rate: 22050
  hop_length: 512
  n_fft: 2048

# Demucs stem separation settings
demucs:
  model_name: "htdemucs_ft"
  device: "cuda"  # Use GPU in production
  stems:
    - "bass"
    - "drums"
    - "other"
    - "vocals"

# Storage settings
storage:
  # Paths will be relative to project root
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  midi_dir: "data/midi"
  models_dir: "data/models"

# Debug settings
debug: false
environment: "production"

# Azure settings (production - load from environment)
azure:
  storage_account: "${AZURE_STORAGE_ACCOUNT}"
  container_name: "${AZURE_CONTAINER_NAME}"
  connection_string: "${AZURE_CONNECTION_STRING}"

# Logging
logging:
  level: "INFO"
  file: "logs/rootzengine.log"
