version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: rootzengine_dev
    volumes:
      - .:/workspaces/rootzengine:cached
    ports:
      - "8000:8000"  # For FastAPI
      - "8888:8888"  # For JupyterLab
    # Keep the container running
    command: >
      sh -c "sleep infinity"
    # Uncomment for GPU support with NVIDIA GPUs
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]