azure:
  # Azure Blob Storage connection string.
  # You can get this from the Azure Portal or Key Vault.
  connection_string: "DefaultEndpointsProtocol=https;AccountName=youraccount;AccountKey=yourkey;EndpointSuffix=core.windows.net"
  
  # Name of the Azure Blob Storage container to use for storing data.
  container: "rootzengine-data"
  
  # (Optional) Azure Key Vault URL for secrets management.
  # Example: "https://my-keyvault.vault.azure.net/"
  key_vault_url: "https://my-keyvault.vault.azure.net/"
  
  # Retry policy for transient Azure errors.
  retry:
    # Maximum number of retry attempts for failed operations.
    max_attempts: 5
    # Delay (in seconds) between retry attempts.
    delay_seconds: 2
